CREATE TYPE "public"."confidence_level" AS ENUM('low', 'moderate', 'high');--> statement-breakpoint
CREATE TYPE "public"."evidence_type" AS ENUM('direct_measurement', 'proxy', 'screening_signal', 'literature_evidence', 'editorial_case_study');--> statement-breakpoint
CREATE TYPE "public"."geographic_level" AS ENUM('facility', 'site', 'watershed', 'county', 'state', 'regional', 'national', 'global', 'literature_cluster');--> statement-breakpoint
CREATE TYPE "public"."layer_group" AS ENUM('official', 'emerging', 'wildlife', 'reproductive', 'legal');--> statement-breakpoint
CREATE TYPE "public"."source_lifecycle" AS ENUM('active_mock', 'planned');--> statement-breakpoint
CREATE TYPE "public"."source_program_tier" AS ENUM('us_v1_core', 'global_v2_planned', 'literature_editorial');--> statement-breakpoint
CREATE TYPE "public"."source_type" AS ENUM('federal_registry', 'federal_research', 'academic_literature', 'journalism', 'global_statistical', 'global_infrastructure', 'hydrology_framework');--> statement-breakpoint
CREATE TYPE "public"."update_cadence" AS ENUM('daily', 'monthly', 'quarterly', 'annual', 'periodic', 'irregular', 'static', 'planned');--> statement-breakpoint
CREATE TABLE "case_studies" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(140) NOT NULL,
	"title" text NOT NULL,
	"subtitle" text NOT NULL,
	"location" text NOT NULL,
	"region" text NOT NULL,
	"geography_id" integer,
	"coordinates" geometry(Point, 4326),
	"date_range_label" varchar(64),
	"category" text NOT NULL,
	"layer_group" "layer_group" DEFAULT 'legal' NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"summary" text NOT NULL,
	"why_it_matters" text NOT NULL,
	"methodology_note" text NOT NULL,
	"hero_eyebrow" text,
	"hero_image_hint" text,
	"evidence_mix" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"key_signals" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"key_findings" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"narrative" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"related_entity_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "case_studies_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "fertility_trends" (
	"id" serial PRIMARY KEY NOT NULL,
	"geography_id" integer,
	"trend_title" text,
	"year" integer NOT NULL,
	"fertility_rate" numeric(12, 4),
	"age_band" varchar(32),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "geographies" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(140) NOT NULL,
	"name" text NOT NULL,
	"geography_type" varchar(64) NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"state_code" varchar(2),
	"country_code" varchar(2) DEFAULT 'US',
	"centroid" geometry(Point, 4326),
	"boundary" geometry(Geometry, 4326),
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "geographies_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "hazardous_sites" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"site_name" text NOT NULL,
	"site_class" varchar(64),
	"status" varchar(64),
	"boundary" geometry(Geometry, 4326),
	"remediation_year" integer,
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "hazardous_sites_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "health_concern_context" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"title" text NOT NULL,
	"concern_type" varchar(120),
	"narrative" text,
	"is_verified" boolean DEFAULT false,
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "health_concern_context_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "industrial_sites" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"facility_name" text NOT NULL,
	"operator_name" text,
	"naics_code" varchar(12),
	"status" varchar(64),
	"location" geometry(Point, 4326),
	"active_year" integer,
	"date_range_label" varchar(64),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "industrial_sites_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "infertility_prevalence" (
	"id" serial PRIMARY KEY NOT NULL,
	"geography_id" integer,
	"prevalence_title" text,
	"year" integer NOT NULL,
	"prevalence_pct" numeric(8, 3),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pfas_sites" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"site_name" text NOT NULL,
	"site_subtype" varchar(64),
	"sampling_matrix" varchar(64),
	"concentration_ppt" numeric(12, 2),
	"observed_year" integer,
	"location" geometry(Point, 4326),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "pfas_sites_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "power_plants" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"plant_name" text NOT NULL,
	"fuel_type" varchar(64),
	"capacity_mw" numeric(12, 2),
	"permit_status" varchar(64),
	"location" geometry(Point, 4326),
	"active_year" integer,
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "power_plants_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "reproductive_indicators" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"indicator_name" text NOT NULL,
	"indicator_year" integer NOT NULL,
	"value" numeric(12, 4),
	"unit" varchar(64),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reproductive_indicators_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "sentinel_species_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"species_name" text NOT NULL,
	"record_year" integer NOT NULL,
	"abnormality_type" varchar(140),
	"severity_score" numeric(8, 3),
	"location" geometry(Point, 4326),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sentinel_species_records_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "source_registry" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(140) NOT NULL,
	"name" text NOT NULL,
	"short_name" text NOT NULL,
	"source_type" "source_type" NOT NULL,
	"lifecycle" "source_lifecycle" NOT NULL,
	"program_tier" "source_program_tier" NOT NULL,
	"layer_groups" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"supported_evidence" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"geographic_scope" text NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"spatial_resolution" text NOT NULL,
	"update_cadence" "update_cadence" NOT NULL,
	"completeness_tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"description" text NOT NULL,
	"caveats" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"confidence_note" text NOT NULL,
	"methodological_use" text NOT NULL,
	"external_url" text NOT NULL,
	"source_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "source_registry_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "sperm_studies" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"study_title" text NOT NULL,
	"publication_year" integer,
	"sample_size" integer,
	"methodology_note" text,
	"outcome_summary" text,
	"location" geometry(Point, 4326),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sperm_studies_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "toxic_release_records" (
	"id" serial PRIMARY KEY NOT NULL,
	"site_id" integer,
	"record_title" text,
	"chemical_name" text NOT NULL,
	"cas_number" varchar(40),
	"reporting_year" integer NOT NULL,
	"quantity_kg" numeric(14, 2),
	"release_medium" varchar(64),
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "update_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"run_label" varchar(140) NOT NULL,
	"layer_group" "layer_group" NOT NULL,
	"source_slug" varchar(140),
	"status" varchar(64) NOT NULL,
	"records_affected" integer DEFAULT 0,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"notes" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "wastewater_sites" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" varchar(160),
	"geography_id" integer,
	"facility_name" text NOT NULL,
	"permit_id" varchar(64),
	"discharge_type" varchar(64),
	"flow_mgd" numeric(10, 2),
	"outfall_location" geometry(Point, 4326),
	"observed_year" integer,
	"category" text,
	"subcategory" text,
	"layer_group" "layer_group" NOT NULL,
	"evidence_type" "evidence_type" NOT NULL,
	"confidence_level" "confidence_level" DEFAULT 'moderate' NOT NULL,
	"geographic_level" "geographic_level" NOT NULL,
	"summary" text,
	"notes" text,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"source_name" text,
	"source_url" text,
	"source_updated_at" timestamp with time zone,
	"ingestion_version" varchar(64) DEFAULT 'v1_draft',
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wastewater_sites_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "case_studies" ADD CONSTRAINT "case_studies_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fertility_trends" ADD CONSTRAINT "fertility_trends_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hazardous_sites" ADD CONSTRAINT "hazardous_sites_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health_concern_context" ADD CONSTRAINT "health_concern_context_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "industrial_sites" ADD CONSTRAINT "industrial_sites_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "infertility_prevalence" ADD CONSTRAINT "infertility_prevalence_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pfas_sites" ADD CONSTRAINT "pfas_sites_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "power_plants" ADD CONSTRAINT "power_plants_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reproductive_indicators" ADD CONSTRAINT "reproductive_indicators_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sentinel_species_records" ADD CONSTRAINT "sentinel_species_records_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sperm_studies" ADD CONSTRAINT "sperm_studies_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "toxic_release_records" ADD CONSTRAINT "toxic_release_records_site_id_industrial_sites_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."industrial_sites"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wastewater_sites" ADD CONSTRAINT "wastewater_sites_geography_id_geographies_id_fk" FOREIGN KEY ("geography_id") REFERENCES "public"."geographies"("id") ON DELETE no action ON UPDATE no action;