CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TYPE layer_group AS ENUM ('official', 'emerging', 'wildlife', 'reproductive', 'legal');
CREATE TYPE evidence_type AS ENUM (
  'direct_measurement',
  'proxy',
  'screening_signal',
  'literature_evidence',
  'editorial_case_study'
);
CREATE TYPE confidence_level AS ENUM ('low', 'moderate', 'high');
CREATE TYPE source_type AS ENUM (
  'federal_registry',
  'federal_research',
  'academic_literature',
  'journalism',
  'global_statistical',
  'global_infrastructure',
  'hydrology_framework'
);
CREATE TYPE geographic_level AS ENUM (
  'facility',
  'site',
  'watershed',
  'county',
  'state',
  'regional',
  'national',
  'global',
  'literature_cluster'
);
CREATE TYPE update_cadence AS ENUM (
  'daily',
  'monthly',
  'quarterly',
  'annual',
  'periodic',
  'irregular',
  'static',
  'planned'
);
CREATE TYPE source_lifecycle AS ENUM ('active_mock', 'planned');
CREATE TYPE source_program_tier AS ENUM ('us_v1_core', 'global_v2_planned', 'literature_editorial');

CREATE TABLE geographies (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(140) UNIQUE NOT NULL,
  name TEXT NOT NULL,
  geography_type VARCHAR(64) NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  state_code VARCHAR(2),
  country_code VARCHAR(2) DEFAULT 'US',
  centroid geometry(Point, 4326),
  boundary geometry(Geometry, 4326),
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE source_registry (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(140) UNIQUE NOT NULL,
  name TEXT NOT NULL,
  short_name TEXT NOT NULL,
  source_type source_type NOT NULL,
  lifecycle source_lifecycle NOT NULL,
  program_tier source_program_tier NOT NULL,
  layer_groups JSONB DEFAULT '[]'::jsonb NOT NULL,
  supported_evidence JSONB DEFAULT '[]'::jsonb NOT NULL,
  geographic_scope TEXT NOT NULL,
  geographic_level geographic_level NOT NULL,
  spatial_resolution TEXT NOT NULL,
  update_cadence update_cadence NOT NULL,
  completeness_tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  description TEXT NOT NULL,
  caveats JSONB DEFAULT '[]'::jsonb NOT NULL,
  confidence_note TEXT NOT NULL,
  methodological_use TEXT NOT NULL,
  origin_site TEXT,
  upstream_datasets JSONB DEFAULT '[]'::jsonb NOT NULL,
  downloadability VARCHAR(48),
  ingestion_method VARCHAR(48),
  external_url TEXT NOT NULL,
  source_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE case_studies (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(140) UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT NOT NULL,
  location TEXT NOT NULL,
  region TEXT NOT NULL,
  geography_id INTEGER REFERENCES geographies(id),
  coordinates geometry(Point, 4326),
  date_range_label VARCHAR(64),
  category TEXT NOT NULL,
  layer_group layer_group DEFAULT 'legal' NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  summary TEXT NOT NULL,
  why_it_matters TEXT NOT NULL,
  methodology_note TEXT NOT NULL,
  hero_eyebrow TEXT,
  hero_image_hint TEXT,
  evidence_mix JSONB DEFAULT '[]'::jsonb NOT NULL,
  key_signals JSONB DEFAULT '[]'::jsonb NOT NULL,
  key_findings JSONB DEFAULT '[]'::jsonb NOT NULL,
  narrative JSONB DEFAULT '[]'::jsonb NOT NULL,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  related_entity_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE industrial_sites (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  facility_name TEXT NOT NULL,
  operator_name TEXT,
  naics_code VARCHAR(12),
  status VARCHAR(64),
  location geometry(Point, 4326),
  active_year INTEGER,
  date_range_label VARCHAR(64),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE toxic_release_records (
  id SERIAL PRIMARY KEY,
  site_id INTEGER REFERENCES industrial_sites(id),
  record_title TEXT,
  chemical_name TEXT NOT NULL,
  cas_number VARCHAR(40),
  reporting_year INTEGER NOT NULL,
  quantity_kg NUMERIC(14,2),
  release_medium VARCHAR(64),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE power_plants (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  plant_name TEXT NOT NULL,
  fuel_type VARCHAR(64),
  capacity_mw NUMERIC(12,2),
  permit_status VARCHAR(64),
  location geometry(Point, 4326),
  active_year INTEGER,
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE hazardous_sites (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  site_name TEXT NOT NULL,
  site_class VARCHAR(64),
  status VARCHAR(64),
  boundary geometry(Geometry, 4326),
  remediation_year INTEGER,
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE pfas_sites (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  site_name TEXT NOT NULL,
  site_subtype VARCHAR(64),
  sampling_matrix VARCHAR(64),
  concentration_ppt NUMERIC(12,2),
  observed_year INTEGER,
  location geometry(Point, 4326),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE wastewater_sites (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  facility_name TEXT NOT NULL,
  permit_id VARCHAR(64),
  discharge_type VARCHAR(64),
  flow_mgd NUMERIC(10,2),
  outfall_location geometry(Point, 4326),
  observed_year INTEGER,
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE reproductive_indicators (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  indicator_name TEXT NOT NULL,
  indicator_year INTEGER NOT NULL,
  value NUMERIC(12,4),
  unit VARCHAR(64),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE sperm_studies (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  study_title TEXT NOT NULL,
  publication_year INTEGER,
  sample_size INTEGER,
  methodology_note TEXT,
  outcome_summary TEXT,
  location geometry(Point, 4326),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE fertility_trends (
  id SERIAL PRIMARY KEY,
  geography_id INTEGER REFERENCES geographies(id),
  trend_title TEXT,
  year INTEGER NOT NULL,
  fertility_rate NUMERIC(12,4),
  age_band VARCHAR(32),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE infertility_prevalence (
  id SERIAL PRIMARY KEY,
  geography_id INTEGER REFERENCES geographies(id),
  prevalence_title TEXT,
  year INTEGER NOT NULL,
  prevalence_pct NUMERIC(8,3),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE sentinel_species_records (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  species_name TEXT NOT NULL,
  record_year INTEGER NOT NULL,
  abnormality_type VARCHAR(140),
  severity_score NUMERIC(8,3),
  location geometry(Point, 4326),
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE health_concern_context (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(160) UNIQUE,
  geography_id INTEGER REFERENCES geographies(id),
  title TEXT NOT NULL,
  concern_type VARCHAR(120),
  narrative TEXT,
  is_verified BOOLEAN DEFAULT FALSE,
  category TEXT,
  subcategory TEXT,
  layer_group layer_group NOT NULL,
  evidence_type evidence_type NOT NULL,
  confidence_level confidence_level DEFAULT 'moderate' NOT NULL,
  geographic_level geographic_level NOT NULL,
  summary TEXT,
  notes TEXT,
  tags JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
  source_name TEXT,
  source_url TEXT,
  source_updated_at TIMESTAMPTZ,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE update_log (
  id SERIAL PRIMARY KEY,
  run_label VARCHAR(140) NOT NULL,
  layer_group layer_group NOT NULL,
  source_slug VARCHAR(140),
  status VARCHAR(64) NOT NULL,
  records_affected INTEGER DEFAULT 0,
  ingestion_version VARCHAR(64) DEFAULT 'v1_draft',
  notes TEXT,
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  started_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  completed_at TIMESTAMPTZ
);
